### ISSUE TITLE
fix for shift operator 

### ISSUE THREAD

**Issue by avral** [devatrun/slimcpplib#1]
<img width="772" alt="Screenshot 2021-12-15 at 00 19 20" src="https://user-images.githubusercontent.com/10092436/146080913-b730b4e2-a025-45a0-91bb-973577fc669f.png">

Having problems with operator! Not working with slimcpplib uint type.
thank you for the lib!

**Comment by devatrun** [comment]
I'm glad you find the library useful! As for the bitwise shift operation, in slimcpp the second operand is always a native unsigned integer type, in fact it is size_t (slim::uint_t) type. Also, for the impossibility of narrowing type conversion, implicit conversion to a smaller type is prohibited by the library, but it can be done explicitly by static_cast<your integer type>.
So there are two options to fix your code:
```c++
const uint256 a = 123;
const uint256 b = 123;

uint256 z = a << static_cast<int>(b); 
```
or
```c++
const uint256 a = 123;
const int b = 123;

uint256 z = a << b; 
```
